### ISSUE TITLE
Default environment variables for connection values

### ISSUE THREAD

**Issue by lonnixOH** [Unleash/unleash-client-ruby#103]
### Describe the feature request

We're just starting to use Unleash and realized that all of our apps need the url, app_name and custom_http_headers set in the code. What we would _like_ to do is set at least DEFAULT_UNLEASH_URL and maybe CUSTOM_HTTP_HEADERS at the platform level that the apps inherit env vars from. This means we don't have to go to each app and provide the url and headers per-app. The app_name would be the only per-app variable, which makes sense because its the only thing that would change between apps. If the URL were to change we could update it in one place and all apps would pick that up upon restart. We can always overwrite the default env vars per-app if needed for testing or modifying headers. 

If this change is implemented the below code blocks would be functionally the same:

No parameters uses the default values specified by `DEFAULT_UNLEASH_URL`, `DEFAULT_UNLEASH_APP_NAME`, `DEFAULT_UNLEASH_CUSTOM_HEADERS`
```
require 'unleash'

@unleash = Unleash::Client.new()
```
Pulling in values from non-default env vars (or just hardcoding values here)
```
require 'unleash'

@unleash = Unleash::Client.new(
  url: ENV['UNLEASH_URL'],
  app_name: ENV['UNLEASH_APP_NAME'],
  custom_http_headers: ENV['UNLEASH_CUSTOM_HEADERS']
)
```

### Background

Each of our apps has its own configuration but also inherits some environment variables provided by the platform. The platform variables usually are for things that are the same across all apps. Since our apps all use the same Unleash api server, the Unleash URL is the same for every app. It would be ideal to only have to specify this in one place instead of in every app. This also prevents the scenario where a developer forgot to add or update the Unleash api server URL and that one app failed to connect. 

### Solution suggestions

I would suggest creating at least 3 new env vars: DEFAULT_UNLEASH_URL, DEFAULT_UNLEASH_APP_NAME, and DEFAULT_UNLEASH_CUSTOM_HTTP_HEADERS

If the corresponding parameter is **not** provided in the call to `Unleash::Client.new()` then check for the correct DEFAULT_ variable and use that if present. 

While the app_name is not something shared by all apps it would be good to have a DEFAULT_ for it so that the naming scheme for these variables is consistent. Potentially there could be a DEFAULT_ variable for every parameter that could be given to `Client.new()`

**Comment by sighphyre** [comment]
Thanks so much for raising this! We're looking into this one this week!

**Comment by sighphyre** [comment]
We ended up speaking a lot more internally than I had originally thought we would. The consensus seems to be that this is a great idea and definitely something we'd like to do. There's some background work that needs to happen before we tackle this directly though:

- We'd like to standardise what we read from the env vars and what names those should use to keep this consistent across all of the SDKs
- Parameter-less constructors make it much more likely that users will spin up multiple client instances within a process, which is almost always the wrong thing to do. We'll need to make this crystal clear in the docs before everyone feels comfortable making this change

So it sounds like we'll look a little bit more closely next quarter at this
