### ISSUE TITLE
Provide a #to_h method for Unleash::Context

### ISSUE THREAD

**Issue by tmaier** [Unleash/unleash-client-ruby#135]
### Describe the feature request

The instance of context should be able to be converted to a hash.
The ruby naming convention is a `#to_h` method to do so.

### Background

Sometimes, one wants to re-use the context set. e.g. to report it to Sentry or any other exception tracker.

### Solution suggestions

Add a `to_h` method to `Unleash::Context`

**Comment by daveleek** [comment]
Thank you for the suggestion and the PR @tmaier, we'll have a look!
