### ISSUE TITLE
Variants in bootstrap file not respected when client is disabled.

### ISSUE THREAD

**Issue by jdurkee-mdsol** [Unleash/unleash-client-ruby#137]
### Describe the bug

When the client is disabled, attempting to call `client.get_variant` always returns the default value, even if the toggle has been defined in the bootstrap config. Seems bootstrapped variant toggles should be loaded and available, just like their standard toggle brethen.

### Steps to reproduce the bug

```ruby
client = Unleash::Client.new(
  disable_client: true,
  url: 'https://example.com',
  bootstrap_config: Unleash::Bootstrap::Configuration.new(
    data: '{
      "version": 1,
      "features": [
        {
          "enabled": true,
          "name": "featureVariantX",
          "strategies": [{ "name": "default" }],
          "variants": [
            {
              "name": "default-value",
              "payload": {
                "type": "string",
                "value": "info"
              },
              "weight": 100,
              "weightType": "variable"
            }
          ]
        }
      ]
    }'
  )
)
pp client.get_variant('featureVariantX', nil)
```

```
[2023-04-27T22:35:22.506886+00:00          Unleash WARN ] : Unleash::Client is disabled! Will only return default (or bootstrapped if available) results!
#<Unleash::Variant:0x00007fd37763c930 @enabled=false, @name="disabled", @payload=nil>
```

### Expected behavior

Toggle should be enabled and the payload should not be nil.

```
[2023-04-27T23:03:03.752292+00:00          Unleash WARN ] : Unleash::Client is disabled! Will only return default (or bootstrapped if available) results!
#<Unleash::Variant:0x00007f0622b23ea8 @enabled=true, @name="featureVariantX", @payload={:type=>"string", :value=>"info"}>
```

### Unleash version

Ruby SDK 4.4.2

### Subscription type

Enterprise

### Hosting type

Hosted by Unleash

### SDK information (language and version)

Ruby SDK 4.4.2

**Comment by andreas-unleash** [comment]
Hi @jdurkee-mdsol , I will bring this to the team and get back to you!

**Comment by sighphyre** [comment]
Hey @jdurkee-mdsol thanks so much for raising this, apologies on the slow turn around time, the relevant people have been on leave. I've put this into our sprint for next week

**Comment by rarruda** [comment]
#138 is now merged.

Thanks for your contribution!
