### ISSUE TITLE
Strategy variants

### ISSUE THREAD

**Issue by kwasniew** [Unleash/unleash-client-ruby#147]
### Describe the feature request

Unleash has a big shift from the feature environment variants to strategy variants to allow more flexible variants based on constraints and segments.
The strategy variants take precedence over the feature environment variants.

### Background

What we do today:
<img width="701" alt="Screenshot 2023-08-14 at 10 04 37" src="https://github.com/Unleash/unleash-client-ruby/assets/1394682/abd69f3b-d51e-4f6b-947e-4e7385daef8d">
What we want to add on top of existing variants:
<img width="679" alt="Screenshot 2023-08-14 at 10 04 49" src="https://github.com/Unleash/unleash-client-ruby/assets/1394682/a86f4ecb-784f-44c1-8024-6d450a6a5c1e">

There's a video showing new strategy variants in action: https://github.com/Unleash/unleash/issues/1550#issuecomment-1645389880

### Solution suggestions

We already have a specification for strategy variants: https://github.com/Unleash/client-specification/blob/main/specifications/16-strategy-variants.json

We already did the migration for other SDKs:
* Node.js: https://github.com/Unleash/unleash-client-node/pull/494/files
* Python: https://github.com/Unleash/unleash-client-python/pull/265
* Java: https://github.com/Unleash/unleash-client-java/pull/205
* Go: https://github.com/Unleash/unleash-client-go/pull/135

The gist of the solution is to first check if the activation strategy has a variant/multiple variants attached. If so, select one of them. If none of the strategies have variants we fall back to the feature environment variants as before (for backwards compatibility). So in the new world each strategy resolves not just to enabled/disabled but when it's enabled it has some variant data attached. It makes the order of strategies matter.

**Comment by gardleopard** [comment]
This is solved in (#148) and released in version 4.5.0.
