### ISSUE TITLE
context_value in Constraint#matches_constraint? throws FrozenError when fronzen-string-literal magic comment is true in the calling context

### ISSUE THREAD

**Issue by thorion3006** [Unleash/unleash-client-ruby#156]
### Describe the bug

When frozen-string-literal magic comment is used in a file that calls the Unleash#is_enabled? method, FrozenError exception is raised if the constraint has case-insensitive enabled.

### Unleash version

v5.3.0

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Ruby v4.5.0

**Comment by sighphyre** [comment]
Thanks for reporting this! That looks like a bug, should be an easy fix
