### ISSUE TITLE
Unleash::Context#to_s does not display all properties

### ISSUE THREAD

**Issue by nissyi-gh** [Unleash/unleash-client-ruby#172]
I want to contribute to unleash-client-ruby, but I am not confident in my English skills, so I use ChatGPT for translation. I apologize for any strange wording or expressions :)

---

## Description

The Unleash::Context#to_s method does not display all the properties of the context object, which can lead to confusion when debugging. Specifically, the current_time property is missing in the output.

## Steps to Reproduce

Create a new Unleash::Context object in IRB:

```ruby
irb(main):001> Unleash::Context.new
```

The output will be:

```ruby
=> 
#<Unleash::Context:0x0000000107b11568
 @app_name=nil,
 @current_time="2024-06-19T15:56:37Z",
 @environment="default",
 @properties={},
 @remote_address=nil,
 @session_id=nil,
 @user_id=nil>
```

Convert the context object to a string:

```ruby
irb(main):002> Unleash::Context.new.to_s
```

The output will be:

```ruby
=> "<Context: user_id=,session_id=,remote_address=,properties={},app_name=,environment=default>"
```

## Expected Behavior

The to_s method should display all properties of the Unleash::Context object, including current_time. For example, the output should be something like:

```ruby
"<Context: user_id=, session_id=, remote_address=, properties={}, app_name=, environment=default, current_time=2024-06-19T15:56:37Z>"
```

## Actual Behavior

The to_s method currently omits the current_time property:

```ruby
"<Context: user_id=,session_id=,remote_address=,properties={},app_name=,environment=default>"
```

# Environment
- Unleash Client Version: "5.0.1"
- Ruby Version: `ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]`
- Operating System: macOS Sonoma 14.5

# Additional Information

Including all properties in the to_s method output would greatly improve the debugging experience by providing complete context information.

---

If this idea is accepted, can I create a pull request myself?

**Comment by rarruda** [comment]
This is a great idea! ☺️

A PR with this contribution would be great and appreciated!

I just request that you double check that all unit test still pass and that rubocop does not raise any issues.
