### ISSUE TITLE
5.0.2 - Initialisation breaks due to attempt to access gemspec.

### ISSUE THREAD

**Issue by regismesquita** [Unleash/unleash-client-ruby#180]
### Describe the bug

% gem install unleash
Successfully installed unleash-5.0.2
1 gem installed

% irb
3.3.3 :001 > require 'unleash'
/Users/regismesquita/.rvm/gems/ruby-3.3.3/gems/unleash-5.0.2/lib/unleash/configuration.rb:7:in `<module:Unleash>': undefined method `metadata' for nil (NoMethodError)

### Steps to reproduce the bug

gem install unleash
irb
require 'unleash'

### Expected behavior

No errors on require.

### Unleash version

5.0.2

### Subscription type

None

### Hosting type

None

**Comment by sighphyre** [comment]
Oh. I think I caused this. So sorry, working on a fix

**Comment by sighphyre** [comment]
@regismesquita Right, we've released 5.0.3, which shouldn't be touching the gemspec like that. Sorry about that!

**Comment by sighphyre** [comment]
Closed by #181

**Comment by regismesquita** [comment]
No problem, thanks for the quick turnaround on this issue.
