### ISSUE TITLE
Custom Context accepts non string value but breaks when case-insensitive is on.

### ISSUE THREAD

**Issue by regismesquita** [Unleash/unleash-client-ruby#189]
### Describe the bug

If one sends a custom context in a non-string format it is accepted by the Unleash library.
i.e.:
```
properties: { foo: { "bar" => "baz" } }
```

The behavior seems to be that if the key is a string, the OPERATOR STR_CONTAINS will check if the constraint_value is a key of the given hash.

In the above scenario , if the Contraint Value is foo STR_CONTAINS "bar", it will return true.

Apparently because of how this line would act:
```
      STR_CONTAINS: ->(context_v, constraint_v){ constraint_v.any?{ |v| context_v.include? v } },
```

as it will translate to:
```
["bar"].any?{ |v| {"bar" => "baz"}.include? v }
```

Which is true.

Other than the issue that this behaviour seems accidental. This also causes an inssue if we enable the case insensitive feature.

As it causes:
```
      context_value = context_value.upcase if self.case_insensitive
```

To try to upcase the Hash.
causing a:
```
 undefined method `upcase' for an instance of Hash (NoMethodError)
```

This can be fixed by doing a to_s on the context_v , or preventing the usage of non-string values.

### Steps to reproduce the bug

create a custom context.
Create a toggle with a Targeting using this custom context in a STR_CONTAINS constraint.
Be sure to set this constraint to case-insensitive.
check the toggle sending a custom context with a hash in the value.

### Expected behavior

Either Reject non-string values or convert non-string values to string values.

### Unleash version

5.12.7

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Ruby, sdk 5.0.5

**Comment by ivarconr** [comment]
Thanks, we will look in to it. 

One thing I noticed is that you pass in a complex object:

```
properties: { foo: { "bar" => "baz" } }
```

This is not expected. Did you try simply passing a string value instead?

```
'properties' => {
        'foo' => 'polarbear'
}
```

**Comment by regismesquita** [comment]
Yes, I ended up implementing that in my code after reviewing the library’s code, which seemed to expect only string values.

Rejecting non-string values for properties appears to be the appropriate solution in this case.
