### ISSUE TITLE
Basic authentication URL connection

### ISSUE THREAD

**Issue by DemitryVolovich** [Unleash/unleash-client-ruby#19]
Hey all, we have the server under a basic authentication and when setting the URL in the initializer like so "http://user:psw@the_url/api" it's not connecting we did a test with plain curl and all worked well and also our NodeJS server works properly with the same URL.
Is there a special thing we need to do to handle this issue?

**Comment by ivarconr** [comment]
Usually you pass the basic authentication as part of the authorization header. It should be a base64 encoded user:password.

https://en.m.wikipedia.org/wiki/Basic_access_authentication

**Comment by DemitryVolovich** [comment]
Thanks, Ivar for the quick response.
I did try this in the header and this didn't work as well, I will check if we have different encoding then base 64.

**Comment by DemitryVolovich** [comment]
So I am getting 308 error code when passing the hashed credentials, is there any configuration we need to do on the server side?

**Comment by ivarconr** [comment]
In order to help you further you must shar more details on how your setup
looks like on the server side.

Ivar

**Comment by DemitryVolovich** [comment]
Thanks, Ivar for the help we fixed the issue which was in our server configuration.
