### ISSUE TITLE
Features url does not appear to be correct

### ISSUE THREAD

**Issue by gingermusketeer** [Unleash/unleash-client-ruby#2]
Had some issues getting this going in a rails app until I realised that I did not have the URL correct.
In order for it to work for me I have to set the `config.url` to `http://localhost:4242/api/client` However this causes the metrics gathering to break due a request being made to `http://localhost:4242/api/client/client/metrics`

Should https://github.com/Unleash/unleash-client-ruby/blob/master/lib/unleash/configuration.rb#L56 include the `client` prefix like the other URLS?

**Comment by rarruda** [comment]
You are correct.

The one previous default feature fetch url was valid only for versions of unleash older then 3.0. Newer ones use the urls you have mentioned. I have now pushed a fix so we are compatible with unleash 3.0 new urls, and added some tests.

Thanks for pointing this out! 👍

**Comment by gingermusketeer** [comment]
@rarruda Many thanks, upgrading to the latest version has resolved it :)
