### ISSUE TITLE
ArgumentError in Unleash::Context#as_json

### ISSUE THREAD

**Issue by Th3-M4jor** [Unleash/unleash-client-ruby#211]
### Describe the bug

At `/lib/unleash/context.rb:26` an `#<ArgumentError: wrong number of arguments (given 1, expected 0)>` can be raised when converting to JSON if any extra options are passed by the json gem.

### Steps to reproduce the bug

I was able to reproduce this by doing

```ruby
require 'json'

JSON.dump(Unleash::Context.new)
```

### Expected behavior

A json is returned and an error is not raised

### Additional context

The fix should be doing what the json gem [recommends](https://github.com/ruby/json/blob/master/README.md#more-examples) and updating the method signature to be `def as_json(*_options)`

### Unleash version

6.2.1, Edge version 19.3.1

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Gem version 6.0.6

**Comment by sighphyre** [comment]
Thanks for the bug report and the suggestion! Fixed in 6.0.7
