### ISSUE TITLE
Exception logging error

### ISSUE THREAD

**Issue by gingermusketeer** [Unleash/unleash-client-ruby#3]
Hi, I noticed that I am getting an exception when the scheduler is trying to log an error:
```
/Users/gingermusketeer/.rubies/ruby-2.5.1/lib/ruby/2.5.0/logger.rb:544:in `error': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
11:25:08 web.1     | 	from /Users/gingermusketeer/.gem/ruby/2.5.1/gems/unleash-0.1.2/lib/unleash/scheduled_executor.rb:27:in `rescue in block (2 levels) in run'
11:25:08 web.1     | 	from /Users/gingermusketeer/.gem/ruby/2.5.1/gems/unleash-0.1.2/lib/unleash/scheduled_executor.rb:22:in `block (2 levels) in run'
11:25:08 web.1     | 	from /Users/gingermusketeer/.gem/ruby/2.5.1/gems/unleash-0.1.2/lib/unleash/scheduled_executor.rb:17:in `loop'
11:25:08 web.1     | 	from /Users/gingermusketeer/.gem/ruby/2.5.1/gems/unleash-0.1.2/lib/unleash/scheduled_executor.rb:17:in
```

Is there an issue with my setup or is this part of the gem? It seems to be caused by there being two arguments to the log error call here: https://github.com/Unleash/unleash-client-ruby/blob/13c91db23254345262be43ab78f690e70af972ec/lib/unleash/scheduled_executor.rb#L27

I was able to reproduce this problem by running `Unleash.logger.error 'one', 'two'` from the rails console.

**Comment by rarruda** [comment]
Thanks for all the testing!

I've pushed now a fix to master. This was an error when using the logging library when handing an exception. Did you by any chance get anything more in the stack trace?

I will be adding a new feature soon, and then cut a new release. 

Hopefully it will help you debug this issue. But note there is something else which is the underlying issue that is raising an exception, which gets rescued there.

**Comment by gingermusketeer** [comment]
No worries!

I was not able to see any more information for the original exception. I have updated to the master branch and tried to reproduce the issue but have not been able to thus far. I will let you know if it comes up again!
