### ISSUE TITLE
Custom strategy

### ISSUE THREAD

**Issue by kceb** [Unleash/unleash-client-ruby#30]
Is there documentation on how to implement a custom strategy?

Looking here: https://unleash.github.io/docs/guides/custom_activation_strategy

It says each client sdk is able to implement their own custom activation strategy. However, I'm not seeing a `strategies` argument when initializing.

**Comment by ivarconr** [comment]
Hi, this actually explained in "https://github.com/Unleash/unleash-client-ruby/issues/28". 

I know @rarruda started on an initiative to make it possible to inject the custom strategies as a parameter, care to give us an update on this effort?

**Comment by rarruda** [comment]
Sorry for the late answer, I had this ready for a few days, but had not uploaded until now. Please look at https://github.com/rarruda/unleash-client-ruby-strategy-companyid.

Note: I only wrote the notes in the README a bit in a hurry, so let me know if i can make things more clear.

**Comment by kceb** [comment]
thanks @rarruda really appreciate that writeup

**Comment by rarruda** [comment]
@kceb Let me know if you have any issues, or if you have any feedback on how to improve the documentation/example implementation.
