### ISSUE TITLE
Inconsistent default result behavior with other Unleash clients

### ISSUE THREAD

**Issue by dlackty** [Unleash/unleash-client-ruby#33]
In Unleash's Ruby client, when feature toggle found disabled, `enabled?` method [returns default result argument](https://github.com/Unleash/unleash-client-ruby/blob/b442c96e8f77d9dd62be15f787fb322d82c6356d/lib/unleash/feature_toggle.rb#L65-L70).

I checked the implementation in [Go](https://github.com/Unleash/unleash-client-go/blob/8e31eee8e5772711671806e87b75f48cd12b87c2/client.go#L256-L267) and [Node](https://github.com/Unleash/unleash-client-node/blob/05421aabd07f4aeb340dcd05fdc0d4b93ba75616/src/client.ts#L62-L68), both just returns `false` instead of default result. 

While digging further into this issue, I found that in those language's clients, they actually use default value (in form of function callback) for the case that toggle's not found.

Unlike in Ruby's implementation, the default value [would be return when toggle not found](https://github.com/Unleash/unleash-client-ruby/blob/master/lib/unleash/client.rb#L41-L44) and toggle not enabled.

**Comment by vinifig** [comment]
Do we have any news about this issue?

**Comment by vinifig** [comment]
Hi! @rarruda, do we have any news about this issue?

**Comment by rarruda** [comment]
This is a "new" functionality of 3.3 branch which is not yet implement in the ruby client. 

https://github.com/Unleash/unleash-client-java/pull/93
https://github.com/Unleash/unleash-client-node/pull/150
https://github.com/Unleash/unleash-client-python/pull/79
https://github.com/Unleash/unleash-client-go/issues/60

The ruby client currently has feature parity with the 3.2 branch of the other clients, where there is only a fallback value, but not the fallback function / lambda.

I will try to get something out soon, but not release it until I have all the other features in the 3.3 branch ready. Sorry for being slow in giving feedback, I have been super busy recently.

**Comment by vinifig** [comment]
@rarruda wow tks! Our team fixed it internally with a monkey patch.
About you been busy, let me know if I can help you someway, I really appreciate your work here!

**Comment by rarruda** [comment]
This should now be solved in PR#40. Hopefully it will be merged into master, and out in a new release soon.

**Comment by rarruda** [comment]
The relevant PR is now merged. It is not yet on a release, so you will need to use it from master right now, until a new release is out (should be soon though). 

Feel free to test it and re-open this issue if you find any issues.
