### ISSUE TITLE
Sidekiq/Console usage in a Rails Application with puma setup

### ISSUE THREAD

**Issue by gbrlcustodio** [Unleash/unleash-client-ruby#50]
I've set up Unleash's Ruby client on a Rails application that is served by a Puma server, and for such I'm creating the client inside the `on_worker_boot` callback and stopping on `before_fork` - as described in the README.

It's has been working flawlessly, but since the client is only started as part of the Puma worker lifecycle, unleash is not available when spinning up a Rails console or inside Sidekiq workers.

Any ideas on how I can proceed with this and let Unleash available in others contexts? I tried to do some initialization magic by creating an initializer file that somehow checks if the current process is a Rails console or Sidekiq instance and have had no luck so far.

**Comment by rarruda** [comment]
So the reason that we do have the block `on_worker_boot` is so that one instance of the unleash client starts per process. 
 See [the puma documentation](https://github.com/puma/puma#clustered-mode) for more details.

> Details into why: Running an instance of the unleash client per process is a hard requirement, as the client needs to manage a few threads of its own and those are not shared across processes. This requires that we start the client in the correct moment. :)

When you are running `Sidekiq` you can hook unleash to [its lifecycle event hooks](https://github.com/mperham/sidekiq/wiki/Deployment#events):

```ruby
# config/initializers/sidekiq.rb
Unleash.configure do |config|
  config.url      = 'http://unleash.herokuapp.com/api'
  config.app_name = Rails.application.class.parent.to_s
  config.environment = Rails.env
end

Sidekiq.configure_server do |config|
  # runs after your app has finished initializing but before any jobs are dispatched.
  config.on(:startup) do
      Rails.configuration.unleash = Unleash::Client.new
  end
  config.on(:quiet) do
    # no need to shutdown unleash early here, as some metrics could go missing
  end
  config.on(:shutdown) do
    Rails.configuration.unleash.shutdown
  end
end
```

To get it to work in the console an option should be to initialize the client when the `Rails::Console` class is loaded (in the console mode):
```ruby
# config/initializers/unleash-console.rb
Unleash.configure do |config|
  config.url      = 'http://unleash.herokuapp.com/api'
  config.app_name = Rails.application.class.parent.to_s
  config.environment = Rails.env
end

if defined?(Rails::Console)
  Rails.configuration.unleash = Unleash::Client.new
end
```

Note that the configure blocks actually don't need to be duplicated everywhere, it only needs to be evaluated once, globally, but before the client is instantiated (wherever that might be applicable).

Could you try the configurations above and see how that works for you?

**Comment by gbrlcustodio** [comment]
Thanks for your quick response regarding this, @rarruda! 

It worked as expected when hooking Unleash's initialization to Sidekiq's lifecycle event hooks, however, using `defined?(Rails::Console)` didn't work for me as it seems that the `Rails::Console` constant is not yet defined while the application is booting.

I ended up with something like this:

```ruby
# config/initializers/unleash.rb
Unleash.configure do |config|
  config.url      = 'http://unleash.herokuapp.com/api'
  config.app_name = Rails.application.class.parent.to_s
  config.environment = Rails.env
end

Rails.application.console do
 Rails.configuration.unleash = Unleash::Client.new
end
```

Notice that I placed Unleash's initialization over there so I won't have to have it scattered all around as you mentioned. It's also responsible for creating an unleash client by using registering blocks to run for the console (using the railtie interface).

Sidekiq's setup worked as you described:

```ruby
# config/initializers/sidekiq.rb

Sidekiq.configure_server do |config|
  config.on(:startup) do
    Rails.configuration.unleash = Unleash::Client.new
  end
  
  config.on(:shutdown) do
    Rails.configuration.unleash.shutdown!
  end
end
```

And finally, the regular puma setup:

```ruby
# config/puma.rb
on_worker_boot do
  Rails.configuration.unleash = Unleash::Client.new
end

before_fork do
  Rails.configuration.unleash.shutdown!
end
```

**Comment by rarruda** [comment]
Cool! thanks for the feedback! I will try to add the new information into the README soon.

**Comment by rarruda** [comment]
Following up in PR #65
