### ISSUE TITLE
Support for Unleash V2

### ISSUE THREAD

**Issue by raresroca05** [Unleash/unleash-client-ruby#52]
Hello @rarruda,

I have been trying to implement the client to my rails monolith (that is part of Moteefe). One of your enterprise clients.
And I have stumbled upon e big error that does not let me implement it, the `request_version` is `2` and the only one supported in the gem is `1`.

This thing does not let me do anything with Unleash.

Can you please tell me what to do or add support for version 2.

Thanks,
Rares and the @moteefe_team

**Comment by rarruda** [comment]
Hi,

We only have a runtime dependency on the [murmurhash](https://github.com/Unleash/unleash-client-ruby/blob/master/unleash-client.gemspec#L26) gem.

Could you send some more details (logs, code, etc) regarding the error you are getting? Is it one of the development dependencies?  Ideally I would like to reproduce the issue here to be better able to help out.

**Comment by raresroca05** [comment]
Hey,

The error is definitely from `lib/unleash/toggle_fetcher.rb` -> at line `51`.
The `response_hash['version']` is `2` and you only support `1`.

The exact error is `Unleash::ToggleFetcher::NotImplemented`.

**Comment by rarruda** [comment]
Thank you! Can you also confirm which version of the unleash server are you using?

I will take a look and get back to you as soon as possible. Thanks for reporting this!

**Comment by raresroca05** [comment]
I think this is the one `Unleash enterprise 4.1.2 (Prod)`

**Comment by ivarconr** [comment]
Thanks for reporting this. 

We changed the version in the response in 4.1 released last week because we added a few more fields to the response. There is no breaking changes and the SDK should just accept anything above V1 and ignore fields it does not care about.

**Comment by raresroca05** [comment]
Thanks, @ivarconr!

So now I just have to update the gem, right?
What version of the gem?

**Comment by raresroca05** [comment]
Because right now, this is happening

`if response_hash['version'] == 1
        features = response_hash['features']
      else
        raise NotImplemented, "Version of features provided by unleash server" \
          " is unsupported by this client."
      end`

**Comment by raresroca05** [comment]
@rarruda @ivarconr ???

**Comment by raresroca05** [comment]
The ERROR:

`DEBUG: [a38fff28-1fd1-4e01-bd1b-4ef151e389ce] [active_model_serializers] fetch()
WARN: [a38fff28-1fd1-4e01-bd1b-4ef151e389ce] [active_model_serializers] ToggleFetcher was unable to fetch from the network, attempting to read from backup file.
DEBUG: [a38fff28-1fd1-4e01-bd1b-4ef151e389ce] [active_model_serializers] Exception Caught: uninitialized constant Unleash::ToggleFetcher::NotImplemented`

**Comment by rarruda** [comment]
I will try to fix this soon, and create a new release with this fix included ASAP. Right now the only workaround would be to monkey patch that method, where you'd skip that version check. 

(see an example here on how to monkey patch: https://www.culttt.com/2015/06/17/what-is-monkey-patching-in-ruby)

**Comment by ivarconr** [comment]
Hi @raresroca05,

Really sorry about the slow response on this one. You should now be able to install the latest version `3.2.3` of the unleash gem and it should now support the latest unleash SDK api. 

For some reason this not properly tested for the ruby SDK before we shipped the 4.1.x release of Unleash. This should not have happened, and we will make sure to improve our processes.

**Comment by raresroca05** [comment]
Thanks a lot @ivarconr
