### ISSUE TITLE
There is not default_variant in the `get_variant` method from `client.rb` at line `64`

### ISSUE THREAD

**Issue by raresroca05** [Unleash/unleash-client-ruby#55]
* There is a problem with the gem in the `get_variant` method of the `client.rb` file.
* The logger uses an undefined method `default_variant`.

**Comment by raresroca05** [comment]
cc @ivarconr @stalet

**Comment by rarruda** [comment]
Thanks for reporting this bug!

The fix should be out now in the latest version of the gem. (3.2.4)

If you have any issues, please either re-open this issue, or create a new one.

**Comment by raresroca05** [comment]
Thanks a lot @ivarconr ;)
