### ISSUE TITLE
Strategy list

### ISSUE THREAD

**Issue by gingermusketeer** [Unleash/unleash-client-ruby#7]
I see that there are a few strategies that are showing up in the unleash server related to this client library: 
![screen shot 2018-07-05 at 4 19 20 pm](https://user-images.githubusercontent.com/1177034/42352512-2aa7a370-8078-11e8-866c-6af7390f47c1.png)

And from the `Unleash::STRATEGIES` constant we have:
```
{:default=>#<Unleash::Strategy::Default:0x00007fe37367f1e8>,
 :gradualRolloutRandom=>#<Unleash::Strategy::GradualRolloutRandom:0x00007fe37367f058>,
 :unknown=>#<Unleash::Strategy::Unknown:0x00007fe37367ef40>,
 :gradualRolloutUserId=>#<Unleash::Strategy::GradualRolloutUserId:0x00007fe37367edb0>,
 :applicationHostname=>#<Unleash::Strategy::ApplicationHostname:0x00007fe37367ec20 @hostname="">,
 :userWithId=>#<Unleash::Strategy::UserWithId:0x00007fe37367ea68>,
 :remoteAddress=>#<Unleash::Strategy::RemoteAddress:0x00007fe37367e8d8>,
 :base=>#<Unleash::Strategy::Base:0x00007fe37367e7c0>,
 :gradualRolloutSessionId=>#<Unleash::Strategy::GradualRolloutSessionId:0x00007fe37367e630>,
 :notImplemented=>#<Unleash::Strategy::NotImplemented: Unleash::Strategy::NotImplemented>}
```

Would it make sense to filter out the `base` class, `unknown` and `notimplemented`?

**Comment by rarruda** [comment]
I should probably remove the `NotImplemented` strategy, and I agree that the `Base` strategy should be filtered out.

But the `Unknown` strategy is implemented in the java client: https://github.com/Unleash/unleash-client-java/tree/master/src/main/java/no/finn/unleash/strategy 
(but not in the node / go clients, and it is not in the spec either: https://github.com/Unleash/unleash/blob/master/docs/activation-strategies.md ) So it is quite debatable if it should be implemented by default in the ruby client.

@ivarconr Any opinion regarding the strategies?

**Comment by ivarconr** [comment]
Clients should not expose internals as registered strategies. The unknown strategy in the java client is there to avoid null handling (written pre java 8 without optional). The client should only register strategies that makes sense.

**Comment by rarruda** [comment]
In that case I will remove the `Unknown` strategy, as it doesn't make sense to keep it around anymore.

**Comment by gingermusketeer** [comment]
Many thanks!
