### ISSUE TITLE
Release v4.0.0. What is the braking change?

### ISSUE THREAD

**Issue by tmaier** [Unleash/unleash-client-ruby#79]
Hi,

you recently released v4.0.0.
What are the breaking changes a user needs to be aware of when upgrading?

I checked the diff, but it is not obvious.
https://github.com/Unleash/unleash-client-ruby/compare/v3.2.5...v4.0.0

Consider to use the GitHub release feature. A nice way to communicate changes is https://keepachangelog.com

Kind regards

**Comment by rarruda** [comment]
Hi! Thanks for the feedback!

There are no `API` breaking changes, but we did:
- change a [few default values](https://github.com/Unleash/unleash-client-ruby/commit/26ae1a56bf5f738a1df4bafd2bce4b5cb9c118bc)
- how we handle the [server api url](https://github.com/Unleash/unleash-client-ruby/commit/61dd59b54ca610f589cf846a1f84a7f702caa40c)
- changed [metrics reporting behavior](https://github.com/Unleash/unleash-client-ruby/commit/ea72260af5db5a456490fcf8934fa79805c12d7a )
- add support for unleash 4.x features (we didn't support the [`projects` query](https://github.com/Unleash/unleash-client-ruby/commit/eb6a2bc7d69bff69755e579f1778066bfd6ab3b8) before)

I understand it is not fully actually fully [SemVer](https://semver.org/), but I thought the change in default behavior was still merited the major bump. (and to signal that we are now supporting most of the [unleash 4.x server features](https://docs.getunleash.io/sdks#server-side-sdk-compatibility-table)).

Was this helpful?

I really like your suggestion of using https://keepachangelog.com . I will try to add one soon.

**Comment by tmaier** [comment]
Hi @rarruda, thanks for your feedback. I am going to close this issue
