### ISSUE TITLE
GradualRolloutRandomStrategy incorrect allocation.

### ISSUE THREAD

**Issue by shadone** [Unleash/unleash-client-ruby#8]
see 
https://github.com/Unleash/client-specification/issues/1#issuecomment-405967451 for details.

**Comment by rarruda** [comment]
https://github.com/Unleash/unleash-client-ruby/blob/master/lib/unleash/strategy/gradual_rollout_random.rb#L20

should be technically equivalent to 

https://github.com/Unleash/unleash-client-java/blob/master/src/main/java/no/finn/unleash/strategy/GradualRolloutRandomStrategy.java#L31-L32

As `Random.rand(1..100)` returns an int between 1 and 100, inclusive.

So setting a `percentage` to `0` would mean that it would never trigger, as it would never be greater or equals to `1`.

Feel free to re-open if you think I might have misread something.
