### ISSUE TITLE
Support semantic versioning for releases

### ISSUE THREAD

**Issue by pravi** [Unleash/unleash-client-ruby#94]
Currently README recommends using ~> 4.0.0. Please follow https://semver.org and update README to explicitly state compliance with semver. This will allow a looser dependency specification ~> 4.0

**Comment by rarruda** [comment]
This is in place now as described in releasing section of the README. We are also adding a CHANGELOG to help keep track of changes between releases as well.

Thanks for your feedback and help!

**Comment by pravi** [comment]
@rarruda thanks!

**Comment by pravi** [comment]
Though installation section still recommends,
gem 'unleash', '~> 4.4.0'

which could be just ~> 4.4
